# Generated by Django 2.2.6 on 2019-10-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_write', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
